// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY-Pq0e7cE-1ypnqCe0Z-zl_DYLEfFbmk',
    appId: '1:3991594550:web:5d8bd28d8df732937eda97',
    messagingSenderId: '3991594550',
    projectId: 'com5b-24',
    authDomain: 'com5b-24.firebaseapp.com',
    storageBucket: 'com5b-24.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtYb27SSro5QnRvaV0ffhAaelUnGhRRRs',
    appId: '1:3991594550:android:9b0debdd1ca97b7e7eda97',
    messagingSenderId: '3991594550',
    projectId: 'com5b-24',
    storageBucket: 'com5b-24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV6B2_SwmS3v2gBDDp4f--yJaleU-WN88',
    appId: '1:3991594550:ios:5c58c0204be24fab7eda97',
    messagingSenderId: '3991594550',
    projectId: 'com5b-24',
    storageBucket: 'com5b-24.appspot.com',
    iosBundleId: 'com.example.practica3ver2',
  );
}
